import { jsPDF } from 'jspdf';
import { KundaliData, NumerologyData } from '../types';

export const generatePDF = (kundali: KundaliData, numerology: NumerologyData | null, langCode: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  const margin = 20;
  let yPos = 20;

  // Colors
  const primaryColor = '#ea580c'; // Saffron
  const secondaryColor = '#9a3412';
  const textColor = '#1f2937';

  // Helper to add a new page
  const checkPageBreak = (heightNeeded: number) => {
    if (yPos + heightNeeded > pageHeight - margin) {
      doc.addPage();
      yPos = 20;
      // Add border to new page
      doc.setDrawColor(primaryColor);
      doc.setLineWidth(1);
      doc.rect(5, 5, pageWidth - 10, pageHeight - 10);
    }
  };

  // Helper to wrap text
  const addWrappedText = (text: string, fontSize: number = 10, fontType: string = 'normal', color: string = textColor) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", fontType);
    doc.setTextColor(color);
    
    const splitText = doc.splitTextToSize(text, pageWidth - (margin * 2));
    const height = splitText.length * (fontSize / 2); // approx height
    checkPageBreak(height + 5);
    
    doc.text(splitText, margin, yPos);
    yPos += height + 5;
  };

  // --- PAGE 1: COVER PAGE ---
  doc.setFillColor(255, 247, 237);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');
  
  // Ornamental Border
  doc.setDrawColor(primaryColor);
  doc.setLineWidth(2);
  doc.rect(10, 10, pageWidth - 20, pageHeight - 20);
  
  yPos = 80;
  doc.setTextColor(primaryColor);
  doc.setFontSize(30);
  doc.setFont("helvetica", "bold");
  doc.text("Sanatan Vedic Jyotish", pageWidth / 2, yPos, { align: 'center' });
  
  yPos += 20;
  doc.setFontSize(16);
  doc.setTextColor(secondaryColor);
  doc.text("Premium Life Report", pageWidth / 2, yPos, { align: 'center' });

  yPos += 40;
  doc.setTextColor(textColor);
  doc.setFontSize(14);
  doc.text(`Prepared for: ${kundali.details.name}`, pageWidth / 2, yPos, { align: 'center' });
  
  yPos += 10;
  doc.setFontSize(12);
  doc.text(`Date of Birth: ${kundali.details.day}/${kundali.details.month}/${kundali.details.year}`, pageWidth / 2, yPos, { align: 'center' });
  
  yPos += 10;
  doc.text(`Time: ${kundali.details.hour}:${kundali.details.minute}`, pageWidth / 2, yPos, { align: 'center' });
  
  yPos += 10;
  doc.text(`Place: ${kundali.details.location}`, pageWidth / 2, yPos, { align: 'center' });

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text("Generated by Sanatan Vedic Jyotish Engine", pageWidth / 2, pageHeight - 15, { align: 'center' });

  // --- PAGE 2: CHARTS & PLANETS ---
  doc.addPage();
  yPos = 20;
  
  doc.setFontSize(16);
  doc.setTextColor(primaryColor);
  doc.text("Lagna Chart (North Indian)", margin, yPos);
  yPos += 15;

  // Draw North Indian Diamond Chart (Simplified Vector Drawing)
  const cx = pageWidth / 2;
  const cy = yPos + 40;
  const size = 40; // half-width
  
  doc.setDrawColor(secondaryColor);
  doc.setLineWidth(1);
  
  // Outer Square
  doc.rect(cx - size, cy - size, size * 2, size * 2);
  
  // Diagonals
  doc.line(cx - size, cy - size, cx + size, cy + size);
  doc.line(cx + size, cy - size, cx - size, cy + size);
  
  // Diamond
  doc.line(cx, cy - size, cx - size, cy);
  doc.line(cx - size, cy, cx, cy + size);
  doc.line(cx, cy + size, cx + size, cy);
  doc.line(cx + size, cy, cx, cy - size);

  // House Numbers (Static for NI Chart structure, simplified placement)
  doc.setFontSize(8);
  doc.setTextColor(textColor);
  // Lagna (Top Middle)
  doc.text(`${kundali.ascendant + 1}`, cx, cy - size + 10, { align: 'center' });
  
  yPos = cy + size + 20;

  // Planetary Table
  doc.setFontSize(14);
  doc.setTextColor(primaryColor);
  doc.text("Planetary Positions", margin, yPos);
  yPos += 10;

  const headers = ["Planet", "Rashi (Sign)", "House", "Degree"];
  const colWidths = [40, 40, 40, 40];
  let startX = margin;
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setFillColor(255, 237, 213);
  doc.rect(margin, yPos - 6, 160, 8, 'F');
  
  headers.forEach((h, i) => {
    doc.text(h, startX, yPos);
    startX += colWidths[i];
  });
  yPos += 10;

  doc.setFont("helvetica", "normal");
  kundali.planets.forEach((p) => {
    startX = margin;
    const data = [
      p.planet + (p.isRetrograde ? " (R)" : ""),
      (p.signIndex + 1).toString(),
      p.house.toString(),
      p.degree.toFixed(2)
    ];
    
    data.forEach((d, i) => {
      doc.text(d, startX, yPos);
      startX += colWidths[i];
    });
    yPos += 8;
  });

  // --- PAGE 3: DETAILED PREDICTIONS ---
  doc.addPage();
  yPos = 20;
  
  doc.setFontSize(16);
  doc.setTextColor(primaryColor);
  doc.text("Life & Character Analysis", margin, yPos);
  yPos += 15;

  // Parse the massive text block from logic
  const predictionSections = kundali.lifePrediction.split('\n\n');
  
  predictionSections.forEach(section => {
    if (section.trim()) {
      // Check if it's a header
      if (section.includes(':')) {
        const parts = section.split(':');
        if (parts[0].length < 50) { // Likely a header
            checkPageBreak(15);
            doc.setFontSize(12);
            doc.setFont("helvetica", "bold");
            doc.setTextColor(secondaryColor);
            doc.text(parts[0], margin, yPos);
            yPos += 6;
            addWrappedText(parts.slice(1).join(':').trim());
            yPos += 4;
            return;
        }
      }
      addWrappedText(section);
      yPos += 5;
    }
  });

  // --- PAGE 4: DOSHAS & REMEDIES ---
  doc.addPage();
  yPos = 20;

  doc.setFontSize(16);
  doc.setTextColor(primaryColor);
  doc.text("Dosha Analysis & Remedies", margin, yPos);
  yPos += 15;

  // Mangal Dosha
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Mangal Dosha Analysis", margin, yPos);
  yPos += 8;
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(kundali.doshas.hasMangalDosha ? '#ef4444' : '#10b981');
  doc.text(kundali.doshas.description, margin, yPos);
  yPos += 15;

  // Remedies
  doc.setTextColor(primaryColor);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Vedic Remedies", margin, yPos);
  yPos += 10;

  kundali.remedies.forEach(r => {
    checkPageBreak(30);
    doc.setTextColor(0);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(`• ${r.type}: ${r.name}`, margin, yPos);
    yPos += 6;
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "italic");
    doc.text(r.description, margin + 5, yPos);
    yPos += 6;
    
    doc.setFont("helvetica", "normal");
    addWrappedText(`Procedure: ${r.procedure}`, 10, 'normal', '#4b5563');
    yPos += 8;
  });

  // --- PAGE 5: NUMEROLOGY (If Available) ---
  if (numerology) {
    doc.addPage();
    yPos = 20;
    
    doc.setFontSize(16);
    doc.setTextColor(primaryColor);
    doc.text("Numerology Report", margin, yPos);
    yPos += 15;

    const numData = [
      { l: "Mulank (Psychic Number)", v: numerology.mulank },
      { l: "Bhagyank (Destiny Number)", v: numerology.bhagyank },
      { l: "Namank (Name Number)", v: numerology.namank },
      { l: "Soul Urge", v: numerology.soulUrge }
    ];

    numData.forEach(d => {
      doc.setFontSize(11);
      doc.setTextColor(0);
      doc.text(`${d.l}: ${d.v}`, margin, yPos);
      yPos += 8;
    });

    yPos += 5;
    doc.setFontSize(12);
    doc.setTextColor(secondaryColor);
    doc.text("Detailed Prediction", margin, yPos);
    yPos += 8;
    addWrappedText(numerology.prediction);

    if (numerology.arrows && numerology.arrows.length > 0) {
        yPos += 10;
        doc.setFontSize(12);
        doc.setTextColor(secondaryColor);
        doc.text("Arrows of Individuality (David Phillips)", margin, yPos);
        yPos += 8;
        
        numerology.arrows.forEach(arrow => {
            addWrappedText(`• ${arrow}`);
        });
    }
  }

  // Save
  doc.save(`${kundali.details.name}_Comprehensive_Report.pdf`);
};